ALTER TABLE users
  ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(30) NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS cnpj VARCHAR(20) NULL AFTER documento,
  ADD COLUMN IF NOT EXISTS senha_hash VARCHAR(180) NULL AFTER cnpj,
  ADD COLUMN IF NOT EXISTS senha_salt VARCHAR(80) NULL AFTER senha_hash,
  ADD COLUMN IF NOT EXISTS cliente_login_ativo TINYINT(1) NOT NULL DEFAULT 1 AFTER senha_salt;
